// Frontend/src/components/ModelInfoForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Image, Upload, Play, Loader2, CircleHelp } from '@lucide/vue';
import CharacteristicsForm from './CharacteristicsForm.vue';
import ImageGuidelines from './ImageGuidelines.vue';
import TrainingStatus from './TrainingStatus.vue';
import TrainingSettingsForm from './TrainingSettings.vue';
import { startTraining } from '../api';
import type {
  ModelInfo,
  ModelType,
  TrainingSettings,
  TrainingResult,
} from '../types';
const model = defineModel<ModelInfo>({ required: true });
const settings = defineModel<TrainingSettings>('settings', { required: true });
const { suggestedDataset } = defineProps<{ suggestedDataset?: File }>();
const emit = defineEmits<{ notice: [message: string]; datasetUsed: [] }>();
function useSuggestedDataset() {
  file.value = suggestedDataset;
  accepted.value = true;
  emit('datasetUsed');
}
const guidelines = ref<InstanceType<typeof ImageGuidelines>>();
const accepted = ref(false);
const fileInput = ref<HTMLInputElement>();
const file = ref<File>();
const dragging = ref(false);
const busy = ref(false);
const error = ref('');
const result = ref<TrainingResult>();
const modelTypes: ModelType[] = ['human', 'item', 'pet'];
function selectFile(files?: FileList | null) {
  dragging.value = false;
  if (!files?.length) return;
  if (files.length !== 1 || !files[0].name.toLowerCase().endsWith('.zip')) {
    emit('notice', 'Please select one ZIP file.');
    return;
  }
  file.value = files[0];
  error.value = '';
}
async function submit() {
  if (busy.value || result.value) return;
  if (!model.value.name.trim())
    return emit('notice', 'Please enter a model name');
  if (!Object.values(model.value.characteristics).some((value) => value !== ''))
    return emit('notice', 'Please fill in the characteristics');
  if (!file.value) return emit('notice', 'Please select a ZIP file');
  if (
    !settings.value.replicateUsername.trim() ||
    !settings.value.replicateApiKey.trim()
  ) {
    emit(
      'notice',
      'Enter your Replicate username and API key in Training Settings.',
    );
    document
      .querySelector<HTMLDetailsElement>('#cloud-connection')
      ?.setAttribute('open', '');
    document.getElementById('replicateUsername')?.focus();
    return;
  }
  busy.value = true;
  error.value = '';
  try {
    // Snapshot settings so edits during the upload cannot change the submitted job.
    result.value = await startTraining(
      file.value,
      { ...model.value, characteristics: { ...model.value.characteristics } },
      { ...settings.value },
    );
    emit('notice', 'Your model training has begun successfully');
  } catch (cause) {
    error.value =
      cause instanceof Error ? cause.message : 'Failed to start training';
  } finally {
    busy.value = false;
  }
}
</script>
<template>
  <form class="model-form" @submit.prevent="submit">
    <fieldset class="training-grid" :disabled="busy || !!result">
      <section class="card panel stack-large">
        <h2>Model Information</h2>
        <div v-if="suggestedDataset" class="notice stack">
          <p>
            A generated portrait is ready to use as a training dataset. This
            replaces the current ZIP selection.
          </p>
          <button
            class="button outline"
            type="button"
            @click="useSuggestedDataset"
          >
            Use generated portrait
          </button>
        </div>
        <div class="field">
          <label for="name">Model Name</label>
          <input
            id="name"
            v-model="model.name"
            placeholder="Enter model name"
          />
        </div>
        <div class="field">
          <label for="training-base">Base Model</label>
          <input
            id="training-base"
            value="FLUX.1 dev (current trainer)"
            readonly
          />
        </div>
        <fieldset class="field">
          <legend>Model Type</legend>
          <div class="radio-row">
            <label v-for="type in modelTypes" :key="type" class="inline">
              <input
                v-model="model.type"
                type="radio"
                name="modelType"
                :value="type"
                @change="model.characteristics = {}"
              />
              {{ type[0].toUpperCase() + type.slice(1) }}
            </label>
          </div>
        </fieldset>
        <div class="stack">
          <span class="field-label">Characteristics</span>
          <CharacteristicsForm
            v-model="model.characteristics"
            :type="model.type"
          />
        </div>
        <div class="stack">
          <div class="spread">
            <span class="field-label">Training Images</span>
            <button
              v-if="accepted"
              type="button"
              class="icon-button"
              aria-label="View image guidelines"
              @click="guidelines?.open()"
            >
              <CircleHelp />
            </button>
          </div>
          <button
            v-if="!accepted"
            type="button"
            class="button outline full"
            @click="guidelines?.open()"
          >
            <Image />
            View Image Guidelines
          </button>
          <template v-else>
            <button
              type="button"
              class="dropzone"
              :class="{ dragging }"
              @click="fileInput?.click()"
              @dragover.prevent="dragging = true"
              @dragleave.prevent="dragging = false"
              @drop.prevent="selectFile($event.dataTransfer?.files)"
            >
              <Upload />
              <span>
                {{
                  dragging
                    ? 'Drop the ZIP file here...'
                    : 'Drag & drop your ZIP file here, or click to select'
                }}
              </span>
            </button>
            <input
              ref="fileInput"
              class="sr-only"
              type="file"
              accept=".zip,application/zip"
              aria-label="Training ZIP file"
              tabindex="-1"
              @change="selectFile(($event.target as HTMLInputElement).files)"
            />
            <div v-if="file" class="card selected-file inline">
              <Image />
              <span>{{ file.name }}</span>
            </div>
          </template>
        </div>
      </section>
      <section class="card panel stack-large">
        <h2>Training Settings</h2>
        <TrainingSettingsForm v-model="settings" />
        <button
          class="button primary full"
          type="submit"
          :disabled="!file || !accepted || busy || !!result"
        >
          <Loader2 v-if="busy" class="spin" />
          <Play v-else />
          {{ busy ? 'Starting Training...' : 'Start Training' }}
        </button>
        <p class="muted">
          Training currently runs on Replicate. Local training support is coming
          next.
        </p>
      </section>
    </fieldset>
    <section v-if="!result && !error" class="card panel training-ready stack">
      <div class="inline">
        <h2>Training Status</h2>
        <span class="badge">{{ busy ? 'Starting' : 'Ready' }}</span>
      </div>
      <p class="muted">
        {{
          busy
            ? 'Uploading your dataset and submitting the training request…'
            : 'Choose a dataset and review your settings to start.'
        }}
      </p>
      <progress v-if="busy" aria-label="Starting training" />
      <div v-else class="empty-progress" />
    </section>
    <TrainingStatus :result="result" :error="error" />
  </form>
  <ImageGuidelines ref="guidelines" @accept="accepted = true" />
</template>

// Frontend/components/training/ModelInfoForm.tsx
'use client';

import { useState, useCallback } from 'react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { ImageGuidelines } from './ImageGuidelines';
import { ModelInfo, ModelType, TrainingStatus, ModelCharacteristics, TrainingSettings, HumanCharacteristics, PetCharacteristics, ItemCharacteristics } from '@/types';
import { HelpCircle, ImageIcon, Play, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { HumanCharacteristicsForm } from './characteristics/HumanCharacteristics';
import { PetCharacteristicsForm } from './characteristics/PetCharacteristics';
import { ItemCharacteristicsForm } from './characteristics/ItemCharacteristics';
import { TrainingStatusPanel } from './TrainingStatus';
import { startTraining } from '@/lib/api/training';
import { useToast } from '@/hooks/use-toast';
import { useDropzone } from 'react-dropzone';
import { Card } from '@/components/ui/card';

interface ModelInfoFormProps {
  onInfoChange: (info: Partial<ModelInfo>) => void;
  trainingSettings: Partial<TrainingSettings>;
}

export function ModelInfoForm({ onInfoChange, trainingSettings }: ModelInfoFormProps) {
  const { toast } = useToast();
  const [modelInfo, setModelInfo] = useState<Partial<ModelInfo>>({});
  const [modelType, setModelType] = useState<ModelType>('human');
  const [imageLocation, setImageLocation] = useState<string>('');
  const [zipFile, setZipFile] = useState<File | null>(null);
  const [showGuidelines, setShowGuidelines] = useState(false);
  const [hasAcceptedGuidelines, setHasAcceptedGuidelines] = useState(false);
  const [characteristics, setCharacteristics] = useState<Partial<ModelCharacteristics>>({});
  const [trainingStatus, setTrainingStatus] = useState<TrainingStatus>({
    status: 'idle',
  });
  const [isLoading, setIsLoading] = useState(false);

  const onDrop = useCallback((acceptedFiles: File[]) => {
    const file = acceptedFiles[0];
    if (file) {
      setZipFile(file);
      setImageLocation(file.name);
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'application/zip': ['.zip'],
    },
    multiple: false
  });

  const handleStartTraining = async () => {
    if (!imageLocation) {
      toast({
        title: 'Error',
        description: 'Please enter the zip file location',
        variant: 'destructive',
      });
      return;
    }

    if (!modelInfo.name || !modelInfo.type || !modelInfo.characteristics) {
      toast({
        title: 'Error',
        description: 'Please fill in all model information',
        variant: 'destructive',
      });
      return;
    }

    setIsLoading(true);
    setTrainingStatus({ status: 'training' });

    try {
      // Start training process
      const response = await startTraining({
        modelInfo: modelInfo as ModelInfo,
        settings: trainingSettings as TrainingSettings,
        imageLocation: imageLocation,
      });

      setTrainingStatus({
        status: 'training',
        replicateUrl: response.replicateUrl,
        modelDestination: response.modelDestination,
      });

      toast({
        title: 'Training Started',
        description: 'Your model training has begun successfully',
      });
    } catch (error) {
      console.error('Training error:', error);
      setTrainingStatus({
        status: 'failed',
        error: error instanceof Error ? error.message : 'Failed to start training',
      });

      toast({
        title: 'Error',
        description: 'Failed to start training. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleTypeChange = (type: ModelType) => {
    setModelType(type);
    setCharacteristics({});
    onInfoChange({ type, characteristics: {} as ModelCharacteristics });
  };

  const handleCharacteristicsChange = (newCharacteristics: ModelCharacteristics) => {
    setCharacteristics(newCharacteristics);
    onInfoChange({ characteristics: newCharacteristics });
  };

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <Label htmlFor="name">Model Name</Label>
        <Input
          id="name"
          placeholder="Enter model name"
          onChange={(e) => onInfoChange({ name: e.target.value })}
        />
      </div>

      <div className="space-y-2">
        <Label>Model Type</Label>
        <RadioGroup
          defaultValue="human"
          onValueChange={(value) => handleTypeChange(value as ModelType)}
        >
          <div className="flex space-x-4">
            <div className="flex items-center space-x-2">
              <RadioGroupItem value="human" id="human" />
              <Label htmlFor="human">Human</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem value="item" id="item" />
              <Label htmlFor="item">Item</Label>
            </div>
            <div className="flex items-center space-x-2">
              <RadioGroupItem value="pet" id="pet" />
              <Label htmlFor="pet">Pet</Label>
            </div>
          </div>
        </RadioGroup>
      </div>

      <div className="space-y-4">
        <Label>Characteristics</Label>
        {modelType === 'human' && (
          <HumanCharacteristicsForm
            onChange={handleCharacteristicsChange}
            value={characteristics as Partial<HumanCharacteristics>}
          />
        )}
        {modelType === 'pet' && (
          <PetCharacteristicsForm
            onChange={handleCharacteristicsChange}
            value={characteristics as Partial<PetCharacteristics>}
          />
        )}
        {modelType === 'item' && (
          <ItemCharacteristicsForm
            onChange={handleCharacteristicsChange}
            value={characteristics as Partial<ItemCharacteristics>}
          />
        )}
      </div>

      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <Label>Training Images ZIP File</Label>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                onClick={() => setShowGuidelines(true)}
              >
                <HelpCircle className="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>View image guidelines</TooltipContent>
          </Tooltip>
        </div>

        <Card
          {...getRootProps()}
          className="border-2 border-dashed p-8 text-center cursor-pointer hover:border-primary transition-colors"
        >
          <input {...getInputProps()} />
          <Upload className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
          {isDragActive ? (
            <p className="text-sm text-muted-foreground">Drop the ZIP file here...</p>
          ) : (
            <p className="text-sm text-muted-foreground">
              Drag & drop your ZIP file here, or click to select
            </p>
          )}
        </Card>

        {zipFile && (
          <Card className="p-3 flex items-center space-x-2">
            <ImageIcon className="h-4 w-4 text-muted-foreground" />
            <span className="text-sm truncate">{zipFile.name}</span>
          </Card>
        )}

        <ImageGuidelines 
          open={showGuidelines}
          onOpenChange={setShowGuidelines}
          onAccept={() => {
            setShowGuidelines(false);
            setHasAcceptedGuidelines(true);
          }}
        />
      </div>

      <div className="space-y-4">
        {hasAcceptedGuidelines ? (
          <>
            <Button
              className="w-full"
              onClick={handleStartTraining}
              disabled={isLoading || trainingStatus.status === 'training' || !zipFile}
            >
              <Play className="mr-2 h-4 w-4" />
              {isLoading ? 'Starting Training...' : 'Start Training'}
            </Button>

            <TrainingStatusPanel status={trainingStatus} />
          </>
        ) : (
          <Button
            variant="outline"
            className="w-full"
            onClick={() => setShowGuidelines(true)}
          >
            <ImageIcon className="mr-2 h-4 w-4" />
            View Image Guidelines
          </Button>
        )}
      </div>
    </div>
  );
}
